FROM debian:bullseye-slim

# To build this image:
# docker build -t voltronic --file Dockerfile.dev .
#
# To rebuild from scratch:
# docker image rm ...
# docker builder prune --all
# docker build -t voltronic --file Dockerfile.dev .

# Copy files.
COPY sources/ /opt/

RUN \
    # Install required packages.
    apt update && apt -y install --no-install-recommends \
        # Curl is used to work with InfluxDB
        curl \
        # These are required to build inverter_poller
        build-essential \
        cmake \
        libspdlog-dev \
        # These are required to work with MQTT
        jq \
        mosquitto-clients \
    # Build inverter_poller binary. It will be placed to /opt.
    && cd /opt/inverter-cli && mkdir bin && cmake . && make && mv inverter_poller /opt/ \
    # Cleanup trash to reduce the size of the container.
    && apt -y clean \
    && apt -y purge build-essential \
    && apt -y purge cmake \
    && apt -y autoremove \
    && rm -rf /opt/inverter-cli


# https://docs.docker.com/engine/reference/builder/#healthcheck
HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt
ENTRYPOINT ["/bin/bash", "/opt/inverter-mqtt/entrypoint.sh"]
