# Version of the syntax used in this file, required for docker-compose itself.
# https://docs.docker.com/compose/compose-file/compose-file-v3
version: '3'

services:
  voltronic-mqtt:
    # If that "build" section is not commented out, then the image will be built
    # locally rather than pulled from the dockerhub.
    #build:
      #context: .
      #dockerfile: Dockerfile.dev

    image: zaychukaleksey/ha-voltronic-mqtt

    container_name: voltronic-mqtt

    # https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
    restart: always

    # Mount config file to the container, so it will be accessible by inverter_poller.
    volumes:
      - ./inverter.conf:/inverter.conf

    devices:
      # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm

      # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2

      # These are required to map RS-232 ports on Wirenboard controller.
      - /dev/ttyMOD1:/dev/ttyMOD1
      - /dev/ttyMOD2:/dev/ttyMOD2
      - /dev/ttyMOD3:/dev/ttyMOD3

    # Temporarily enable debug logging.
    command: -d

  # Used to auto-update the application as new version is released.
  # Comment the whole section out in case, if you don't want auto-update.
  watchtower:
    # Please see the following for configuration options: https://containrrr.dev/watchtower/arguments/
    image: containrrr/watchtower
    container_name: "auto-updater"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Check for updates every 5 minutes.
    command: voltronic-mqtt --interval 300
